limits :
    start: 1.0
    end: 8.0
equation:
    d2u: 11.0
    du: 3.0
    u: 0.0
    rightSide: 7.0
elemsNum: 20000
borderConditions:
    left:
        type: 'dirichlet'
        value: -6.0
    right:
        type: 'neumann'
        value: -6.0